services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "WorkPac_Dev_2024!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5900:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  seq:
    image: datalust/seq:latest
    ports:
      - "5441:5341"
      - "8081:80"
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: "WorkPac_Seq_2024!"

volumes:
  sql_data:
